### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by nikshepsvn** [AP-Atul/Torpido#3]
any examples of this in action?

**Comment by ap-atul** [comment]
Yes. I have tweajed the settings and git quit good results

**Comment by nikshepsvn** [comment]
I meant to ask you if there are any before to after footage available to look at

**Comment by ap-atul** [comment]
I might add some for demo

**Comment by ap-atul** [comment]
Added a simple one in the readme, its not perfect but if you tweak the setting when launched, the output will differ
